language: java

sudo: false

cache:
  directories:
  - $HOME/.m2

jdk:
  - oraclejdk8

os:
  - linux

install: true
script: mvn test -B

after_success:
  - bash <(curl -s https://codecov.io/bash)
