language: java

sudo: false

notifications:
  email: false

cache:
  directories:
  - $HOME/.m2

jdk:
  - oraclejdk8

before_install:
  - pip install --user codecov

after_script:
  - codecov
