language: java

sudo: false

notifications:
  email: false

cache:
  directories:
  - $HOME/.m2

jdk:
  - oraclejdk8

os:
  - linux

install: true

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)
